version: '3.3'
services:
  spacejoywebv2:
    container_name: spacejoywebv2
    image: spacejoyio/spacejoywebv2
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://auth.spacejoy.com
